config/routes.rb
Rails.application.routes.draw do
  get 'help/detail'
  post 'auth/:provider/callback', to: 'sessions#create'
  get :signout, to: 'sessions#destroy'
  get 'auth/failure', to: redirect('/')
  root 'help#detail'
  resources :messages
  resources :identities, only: :new

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  def self.from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :authenticate

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authenticate
      if Rails.env.production?
        authenticate_or_request_with_http_basic('Enter Password') do |u, p|
          u == ENV['USER_EDITABLE'] && p == ENV['PASSWORD_EDITABLE']
        end
      end
    end

end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  before_action :authenticate, except: [:detail]

  def detail
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  def new
    @identity = env['omniauth.identity']
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body).merge(user_id: current_user.id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to messages_path, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed out!"
  end

  def failure
    redirect_to root_path, alert: "Authentication failed, please try again."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/help/detail.html.haml
%h1
  ポリアンナメールサービス

%p
  いつかの「あなた」の「よかった」がいつかの「あなた」に届きます

app/views/identities/new.html.haml
%h1
  New Account

= form_tag "/auth/identity/register" do
  - if @identity && @identity.errors.any?
    %div.error_messages
      %h2
        = pluralize(@identity.errors.count, "error")
        prohibited this account from being saved:
      %ul
        - @identity.errors.full_messages.each do |msg|
          %li
            = msg
  %div.field
    = label_tag :name
    %br
    = text_field_tag :name, @identity.try(:name)
  %div.field
    = label_tag :email
    %br
    = text_field_tag :email, @identity.try(:email)
  %div.field
    = label_tag :password
    %br
    = password_field_tag :password
  %div.field
    = label_tag :password_confirmation
    %br
    = password_field_tag :password_confirmation
  %div.actions
    = submit_tag "Register"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollyanna</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.haml
= form_for @message do |f|
  - if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :body
    = f.text_area :body

  .actions
    = f.submit 'Save'

app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', @message
\|
= link_to 'Back', messages_path

app/views/messages/index.html.haml
%h1 Listing messages

%table
  %tr
    %th
    %th
    %th

  - @messages.each do |message|
    %tr
      %td= link_to 'Show', message
      %td= link_to 'Edit', edit_message_path(message)
      %td= link_to 'Destroy', message, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Message', new_message_path

app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', messages_path

app/views/messages/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path